# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67815cf7315ee5ebcf5112b382ebf096b4bbb31cf651dab8f76610b575d08b2f94742691f2686229d2497fc01dfe9965402209d5d7c8908898db3ad04fedaafd

test:
  secret_key_base: 4d7868a6e7c760d7c903a03acc3c8ed03ba861f6471eb4a2aac7fed1a9500551fa72e2d3fbfd332369e516a6527e77dadad8639d99a71018daa75d3a1744e76f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
